"""
Integration test: post-login HTML → keyword filtering → AI Playwright generation.

Scenario
--------
A QA engineer logs into an internal CRM and saves the dashboard HTML for
reference. The HTML contains real customer PII (names, emails, phone numbers),
internal hostnames, an API key, and a session token embedded in a <script>.

Before handing the HTML to an AI (to generate a Playwright test that navigates
the dashboard), all sensitive values are tokenised with kw-filter.  The AI
writes Playwright code using the safe tokens.  kw-filter then restores the
originals so the final script is ready to run against the real environment.

Workflow
--------
1. dashboard.html   (post-login HTML — contains real PII / credentials)
        │
        ▼  kw-filter replace
2. dashboard_tokenised.html  ([[KW_XXXX]] everywhere)
        │
        ▼  send to AI (simulated here by _ai_generate_playwright)
3. playwright_tokens.ts  (Playwright code with tokens)
        │
        ▼  kw-filter restore
4. playwright_final.ts  (working script with real values)
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))
from kw_tools import cmd_replace, cmd_restore
from conftest import ns_replace, ns_restore

# ── Fixtures ──────────────────────────────────────────────────────────────────

DASHBOARD_HTML = """\
<!DOCTYPE html>
<html lang="zh-TW">
<head><meta charset="UTF-8"><title>CRM Dashboard — Acme Corp</title></head>
<body>
  <header>
    <span id="current-user">alice.wu@acme-corp.internal</span>
    <span id="api-key" style="display:none">sk-prod-4f8e2a7b9c1d3e5f</span>
    <a href="https://crm.acme-corp.internal/logout">Logout</a>
  </header>

  <section id="customer-list">
    <table id="tbl-customers">
      <tbody>
        <tr data-id="C001">
          <td>王大明</td>
          <td>wang.daming@gmail.com</td>
          <td>0912-345-678</td>
          <td><button data-action="edit" data-id="C001">編輯</button></td>
        </tr>
        <tr data-id="C002">
          <td>李小華</td>
          <td>lisa.hua@outlook.com</td>
          <td>0978-901-234</td>
          <td><button data-action="edit" data-id="C002">編輯</button></td>
        </tr>
      </tbody>
    </table>
  </section>

  <script>
    const SESSION_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.acme2024";
    const BASE_URL = "https://api.acme-corp.internal:8443/v2";
  </script>
</body>
</html>
"""

KEYWORDS = """\
alice.wu@acme-corp.internal
wang.daming@gmail.com
0912-345-678
lisa.hua@outlook.com
0978-901-234
acme-corp.internal
sk-prod-4f8e2a7b9c1d3e5f
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.acme2024
"""

# Values that must NEVER appear in any tokenised output sent to AI
SENSITIVE_VALUES = [
    "alice.wu@acme-corp.internal",
    "wang.daming@gmail.com",
    "0912-345-678",
    "lisa.hua@outlook.com",
    "0978-901-234",
    "acme-corp.internal",
    "sk-prod-4f8e2a7b9c1d3e5f",
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.acme2024",
]


def _ai_generate_playwright(tokenised_html: str) -> str:
    """Simulate what an AI returns when given tokenised dashboard HTML.

    In production this would be an API call to Claude / GPT.  Here we
    hard-code a realistic Playwright TypeScript test that references every
    token found in the tokenised input so the test can verify end-to-end restore.
    """
    tokens = re.findall(r'\[\[KW_[0-9A-F]{8}\]\]', tokenised_html)
    unique_tokens = list(dict.fromkeys(tokens))   # preserve order, deduplicate

    # Build a lookup so generated code is readable regardless of token order
    t = {i: tok for i, tok in enumerate(unique_tokens)}
    # Keyword list (longest-first) determines assignment order:
    # 0: alice.wu@acme-corp.internal (longest email containing the domain)
    # 1: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.acme2024 (JWT session token)
    # 2: wang.daming@gmail.com
    # 3: lisa.hua@outlook.com
    # 4: sk-prod-4f8e2a7b9c1d3e5f (API key)
    # 5: acme-corp.internal (domain suffix matched inside the longer tokens above)
    # 6: 0912-345-678
    # 7: 0978-901-234

    def tok(i: int) -> str:
        return t.get(i, f'[[MISSING_{i}]]')

    lines = [
        "import { test, expect } from '@playwright/test';",
        "",
        "// Generated by AI from tokenised CRM dashboard HTML",
        f"const BASE_URL = 'https://crm.{tok(5)}/dashboard';",
        f"const SESSION   = '{tok(1)}';",
        f"const API_KEY   = '{tok(4)}';",
        "",
        "test.use({{",
        f"  storageState: {{ cookies: [], origins: [] }},",
        "}});",
        "",
        "test('customer list renders correct rows', async ({ page }) => {",
        f"  await page.goto(BASE_URL);",
        "",
        "  // Verify logged-in user indicator",
        f"  await expect(page.locator('#current-user'))",
        f"    .toHaveText('{tok(0)}');",
        "",
        "  // Verify first customer row",
        f"  const row1 = page.locator('[data-id=\"C001\"]');",
        f"  await expect(row1.locator('td').nth(1)).toHaveText('{tok(2)}');",
        f"  await expect(row1.locator('td').nth(2)).toHaveText('{tok(6)}');",
        "",
        "  // Verify second customer row",
        f"  const row2 = page.locator('[data-id=\"C002\"]');",
        f"  await expect(row2.locator('td').nth(1)).toHaveText('{tok(3)}');",
        f"  await expect(row2.locator('td').nth(3)).toHaveText('{tok(7)}');",
        "});",
        "",
        "test('edit button triggers API call with correct auth', async ({ page }) => {",
        f"  await page.goto(BASE_URL);",
        f"  const [req] = await Promise.all([",
        f"    page.waitForRequest(r => r.url().includes('{tok(5)}')),",
        f"    page.locator('[data-id=\"C001\"] button').click(),",
        f"  ]);",
        f"  expect(req.headers()['authorization']).toBe(`Bearer {tok(1)}`);",
        "});",
    ]
    return "\n".join(lines) + "\n"


# ── Tests ─────────────────────────────────────────────────────────────────────

class TestDashboardHtmlWorkflow:
    """Unit-level tests for each step of the replace → AI → restore pipeline."""

    def _setup(self, tmp_path):
        html = tmp_path / "dashboard.html"
        html.write_text(DASHBOARD_HTML, encoding="utf-8")
        kw = tmp_path / "keywords.txt"
        kw.write_text(KEYWORDS, encoding="utf-8")
        mapping = tmp_path / "mapping.json"
        return html, kw, mapping

    def test_step1_replace_removes_all_sensitive_values(self, tmp_path):
        """After replace, no sensitive value should remain in the HTML."""
        html, kw, mapping = self._setup(tmp_path)
        cmd_replace(ns_replace(kw, html, mapping))
        tokenised = html.read_text(encoding="utf-8")
        for val in SENSITIVE_VALUES:
            assert val.lower() not in tokenised.lower(), (
                f"Sensitive value still present after replace: {val!r}"
            )

    def test_step1_tokens_injected(self, tmp_path):
        """replace must inject [[KW_...]] tokens into the HTML."""
        html, kw, mapping = self._setup(tmp_path)
        cmd_replace(ns_replace(kw, html, mapping))
        tokenised = html.read_text(encoding="utf-8")
        assert "[[KW_" in tokenised

    def test_step1_mapping_contains_all_keywords(self, tmp_path):
        """mapping.json must contain every keyword from the keyword list."""
        html, kw, mapping = self._setup(tmp_path)
        cmd_replace(ns_replace(kw, html, mapping))
        m = json.loads(mapping.read_text(encoding="utf-8"))
        canonical_values = {v.lower() for v in m.values()}
        for val in SENSITIVE_VALUES:
            assert val.lower() in canonical_values, (
                f"Keyword missing from mapping: {val!r}"
            )

    def test_step2_ai_output_contains_only_tokens(self, tmp_path):
        """AI-generated Playwright code must not contain any sensitive value."""
        html, kw, mapping = self._setup(tmp_path)
        cmd_replace(ns_replace(kw, html, mapping))
        tokenised = html.read_text(encoding="utf-8")

        pw_code = _ai_generate_playwright(tokenised)
        assert "[[KW_" in pw_code, "AI output should reference tokens"
        for val in SENSITIVE_VALUES:
            assert val.lower() not in pw_code.lower(), (
                f"Sensitive value leaked into AI output: {val!r}"
            )

    def test_step3_restore_recovers_real_values(self, tmp_path):
        """After restore, the Playwright file must contain real values and no tokens."""
        html, kw, mapping = self._setup(tmp_path)
        cmd_replace(ns_replace(kw, html, mapping))
        tokenised = html.read_text(encoding="utf-8")

        pw_tokens = tmp_path / "test_dashboard.ts"
        pw_tokens.write_text(_ai_generate_playwright(tokenised), encoding="utf-8")

        cmd_restore(ns_restore(mapping, pw_tokens))
        restored = pw_tokens.read_text(encoding="utf-8")

        assert "acme-corp.internal" in restored
        assert "alice.wu@acme-corp.internal" in restored
        assert "wang.daming@gmail.com" in restored
        assert "sk-prod-4f8e2a7b9c1d3e5f" in restored
        assert "[[KW_" not in restored, "No tokens should remain after restore"

    def test_step3_session_token_restored(self, tmp_path):
        """JWT session token must survive the full replace → restore cycle."""
        html, kw, mapping = self._setup(tmp_path)
        cmd_replace(ns_replace(kw, html, mapping))
        tokenised = html.read_text(encoding="utf-8")

        pw_tokens = tmp_path / "test_session.ts"
        pw_tokens.write_text(_ai_generate_playwright(tokenised), encoding="utf-8")
        cmd_restore(ns_restore(mapping, pw_tokens))

        restored = pw_tokens.read_text(encoding="utf-8")
        assert "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.acme2024" in restored

    def test_full_roundtrip_html_unchanged(self, tmp_path):
        """Replace then restore on the original HTML must yield the exact original."""
        html, kw, mapping = self._setup(tmp_path)
        original = html.read_text(encoding="utf-8")

        cmd_replace(ns_replace(kw, html, mapping))
        assert html.read_text(encoding="utf-8") != original   # tokens inserted

        cmd_restore(ns_restore(mapping, html))
        assert html.read_text(encoding="utf-8") == original   # perfectly restored

    def test_full_roundtrip_no_token_leakage(self, tmp_path):
        """End-to-end: no [[KW_...]] token should appear in the final Playwright file."""
        html, kw, mapping = self._setup(tmp_path)

        cmd_replace(ns_replace(kw, html, mapping))
        tokenised = html.read_text(encoding="utf-8")

        pw_tokens = tmp_path / "pw.ts"
        pw_tokens.write_text(_ai_generate_playwright(tokenised), encoding="utf-8")

        cmd_restore(ns_restore(mapping, pw_tokens))
        final = pw_tokens.read_text(encoding="utf-8")

        assert "[[KW_" not in final
        for val in SENSITIVE_VALUES:
            # Real values must be back
            if val in DASHBOARD_HTML:
                assert val in final or val.lower() in final.lower()


class TestDashboardExampleFiles:
    """Verify the committed example files work with the full workflow."""

    EXAMPLES_DIR = Path(__file__).parent.parent / "examples" / "playwright"

    def test_example_files_exist(self):
        assert (self.EXAMPLES_DIR / "keywords.txt").exists()
        assert (self.EXAMPLES_DIR / "dashboard.html").exists()

    def test_example_html_contains_expected_pii(self):
        """Sanity-check: example HTML must contain the sensitive values we claim to filter."""
        html = (self.EXAMPLES_DIR / "dashboard.html").read_text(encoding="utf-8")
        for val in [
            "alice.wu@acme-corp.internal",
            "wang.daming@gmail.com",
            "sk-prod-4f8e2a7b9c1d3e5f",
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.acme2024",
        ]:
            assert val in html, f"Expected PII not found in example HTML: {val!r}"

    def test_example_workflow(self, tmp_path):
        """Full replace + restore on committed example files must round-trip cleanly."""
        import shutil
        html = tmp_path / "dashboard.html"
        kw = tmp_path / "keywords.txt"
        mapping = tmp_path / "mapping.json"
        shutil.copy(self.EXAMPLES_DIR / "dashboard.html", html)
        shutil.copy(self.EXAMPLES_DIR / "keywords.txt", kw)

        original = html.read_text(encoding="utf-8")

        cmd_replace(ns_replace(kw, html, mapping))
        tokenised = html.read_text(encoding="utf-8")

        # Verify no PII leaks
        assert "alice.wu@acme-corp.internal" not in tokenised
        assert "sk-prod-4f8e2a7b9c1d3e5f" not in tokenised
        assert "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.acme2024" not in tokenised
        assert "[[KW_" in tokenised

        # Restore and verify full round-trip
        cmd_restore(ns_restore(mapping, html))
        assert html.read_text(encoding="utf-8") == original
